# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache:
  packages: yes
  directories: $TRAVIS_BUILD_DIR/_bookdown_files

sudo: false
r_packages:
  bookdown

pandoc_version: 1.19.2.1

env:
  global:
    secure: GITHUB_TOKEN

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
