# Hypothesis and objectives

## Hypothesis

\acr{IBD} is a gastrointestinal disease preferentially affecting the lower intestinal tract and causing lesions on the epithelium. 
Bacteria interact with a host's epithelium, as well as, with many other variables.
There are data integration methods for a variety of purposes, including methods to most effectively identify relationships between variables. 
These methods have not been used as much in \acr{IBD} to determine which bacteria is related a host's genes. 

We hypothesize that the expression state of the epithelium , in tandem with the **microorganisms present, might help determine whether patients are suffering \acr{IBD} when environmental factors are taken into account**.

## Objectives

The main objective of this thesis was determining the relationships between the microbiome and gene expression in the intestinal mucosa. 
Thus we sought to identify those microorganisms and genes associated with \acr{IBD}.

-   Identify any relationships between intestinal mucosal gene expression and the microbiome's presence in the intestine. 

-   Determine the influence and mucosal relationships of clinical variables such as location (colon and ileum), disease status, sex, age, treatment received, etc. on the microbiota, the microbiome and the attendant mucosal relationship.

-   Identify those groups of mechanisms underlying the interactions between the microbiome and the mucosa in \acr{IBD}.
