# Acknowledgments

A la directora, tutora, jefa i tants papers que fas, moltes gràcies Azu per haver estat a sobre de la tesis, he aprés molt de tot sobre com treballar amb intensitat i eficiencia, tocant de peus a terra. 
També per preguntar i tenir presents sobre com es pot fer servir això i com pot ajudar cada idea que tenia. 

Gràcies Juanjo per donar-me la oportunitat d'entrar a IDIBAPS i per tota la ajuda al llarg d'aquests anys per apendre a ser un bioinformàtic independent. 
Sempre has estat disponible quan no sabia com seguir i aportaves alguna idea o paquet per probar. 

A tot el laboratori per el bon ambient que hi ha hagut al llarg d'aquests anys, fent les alegries més grans  i les adversitats més lleugeres. 
Cadascú ho ha fet a la seva manera: a l'Ana per ser el complement perfecte de l'equip bioinformàtic i sempre estar disponible per aconsellar-me. 
L'Alba pel seu optimisme, perseverancia i ambició, también por tu buen criterio diseñando, espero que algo se me pegue.
A l'Isa pel seu detallisme i exemple de fer bé les coses, les orquidies siempre están preciosas!
La Marisol per la seva senzillesa i estar sempre pendent dels petits detalls de la paperasa. 
La Elisa per encomanar la seva alegria i il·lusió que mai defalleixen.
La Victòria per la seva paciència i consells sobre com descriure els projectes. 
L'Angela por tu paciencia con mis salidas friquis.
La Míriam perqué sempre ens toca moure trastos, a veure si algun dia montem el wallapop científic! i l'Iris que sempre té alguna cosa a aportar.  
Moltes gràcies a totes, només lamento no haver aprés més de vosaltres. 

Hi ha persones que estan sempre com la Pepa, gràcies per no tancar-me mai el email, i altres que marxen a altres projectes. 
Gràcies per compartir una part d'aquest projecte amb mí:
l'Aida per la teva acollida al lab i per tota l'empenta que ha posat en aquests anys, moltes gràcies per introduir-me en el món de la microbiota!
La Montse per organitzar els primers viatges fòra i ensenyar-me a organitzar-me.
La Núria per introduir-me en el grup i animar-me a fer el doctorat amb l'Azu.
També en Daniel pel curset de processament de RNAseq. 

A tots de l'equip de l'hospital, per intentar entendre aquestes caixes negres de les tesis i ajudar a que no perdi de vista l'objectiu de la recerca; en especial al Julià, per fer sempre les millors preguntes i a la Maica per resoldre molts dubtes a l'inici.

A tot l'equip del Pau que em van acompanyar en els meus primers passos en la investigació, la Bea, la Júlia, la Délia, la Mar, en Luis, la Elisa...
Alguns que ja no estan per la planta 3 com en Josep o la Carolina. 

A tota la familia, els que estan més aprop i els que estan més lluny. 
Als pares per seguir amb interès tot el procés i procurar entendre alguna cosa.
A la Maria per convidar-me sovint a casa seva a descansar.
A la Maria del Mar per la teva alegria i plantejar reptes amb el python. 
A la Marta pels consells, el cotxe i les excursions. 
A l'Ana per seguir amb interés la investigació i estar pendent dels avanços sobre la microbiota. 
A l'Albert per convidar-me a dinar sovint i conèixer racons i històries de Barcelona. 

Als amics en especial, en Mario per posar la casa tantes vegades al llarg de la tesis, un día tienes que venir a la mía!
L'Albert Mateo per les refrescants sortides en bici i excursions, a ver si hacemos más y con todos!
L'Alejandro que sempre ha estat un suport moral com a doctorand.
A l'Edu per estar sempre disposat a acostar-me en cotxe o trobar un lloc fàcil d'arribar en transport públic. 
En Frederic per compartir molts dinars, penes i alegries.
En Joan per marcar el camí, sempre has estat per davant! i l'Aleix, espero que la bioinformàtica vagi a més! 


Als amics d'Obenc, el Cristian pels canvis que hem viscut aquests anys.
En Daniel per ensenyar-me que el temps no es barrera per fer coses (encara no m'has presentat els teus gossos!). 
A en Lluís que tampoc no pares mai i m'has transmés la teva gran ambició.
A en Ricard per totes les discussions sobre el futur profesional, de la programació, els jocs, pel·lícules i tantes coses, segur que trobes una manera de passar al seguent nivell!
A en Joaquín per ensenyar-me el món empresarial de software i tants detalls tècnics. 
A tots els que han vingut a futbol, en especial al Josep Mª per ser l'incansable impulsor i treure gent de sota les pedres i a en Josep per ser el més constant, ja xutaré més sovint!

I also received  many help from numerous and anonymous people from several corners of the world.
They might have shared some interesting tip, advice or experiences on Twitter, or answered my questions on [Bioconductor's support forum](https://support.bioconductor.org), [Biostars](https://biostars.org), [Bioinformatics SE](https://bioinformatics.stackexchange.com/) or Stackexchange network. 
Also those that made and provided the software for free that made all this possible on your own time, R core, CRAN, Bioconductor and rOpenSci teams, package developers and maintainers of the ~500 packages I use. 

Thanks to those that made possible accessing their data without problems.
Dr. Häsler for kindly providing data of the samples from their cohort and Dr. Cristian Hernández and Dr. Mark S. Silverber for their collaboration and selfless sharing the data of their cohort.

Last but not least, those without all this could not have been possible: 
Thanks to all the patients that participated on the studies and allowed clinicians to collect samples and data for research. 
I hope that the knowledge we gain with on this thesis and other studies will bring us closer to heal this disease. 
