# (APPENDIX) Appendix {-}

# Online resources

Some links that I found useful on the thesis and could be useful if you are interested on the multi-omics field.

-   [Awesome multi-omics](https://github.com/mikelove/awesome-multi-omics): An online repository of references to multi-omics methods. Reproduced here with their references [^references-1]:

    [^references-1]: Consulted on 2021/11/10 from <https://github.com/mikelove/awesome-multi-omics>

| Method                         | Publication                   |
| :----------------------------: | :---------------------------: |
| SCCA                           | [@parkhomenko2009]            |
| PCCA                           | [@waaijenborg2008]            |
| PMA                            | [@witten2009]                 |
| sPLS                           | [@lêcao2009]                  |
| gesca                          | [@hwang2009]                  |
| Regularized dual CCA           | [@soneson2010]                |
| RGCCA                          | [@tenenhaus_regularized_2011] |
| SNMNMF                         | [@zhang2011]                  |
| scca                           | [@lee2011]                    |
| STATIS                         | [@abdi2012]                   |
| joint NMF                      | [@zhang2012]                  |
| sMBPLS                         | [@li2012]                     |
| Bayesian group factor analysis | [@virtanen2012]               |
| RIMBANET                       | [@zhu2012]                    |
| FactoMineR                     | [@abdi2013]                   |
| JIVE                           | [@lock2013a]                  |
| pandaR                         | [@schlauch2017]               |
| omicade4                       | [@meng2014]                   |
| STATegRa                       | [@planell2021]                |
| Joint factor model             | [@ray2014]                    |
| GFAsparse                      | [@bunte2016]                  |
| Sparse CCA                     | [@chen2013]                   |
| CCAGFA                         | [@leppäaho2017]               |
| CMF                            | [@klami2014]                  |
| MOGSA                          | [@meng2018]                   |
| iNMF                           | [@yang2016b]                  |
| BASS                           | [@zhao2015]                   |
| imputeMFA                      | [@voillet2016]                |
| PLSCA                          | [@beaton2016]                 |
| mixOmics                       | [@singh2019]                  |
| mixedCCA                       | [@yoon2019]                   |
| SLIDE                          | [@gaynanova2017]              |
| fCCAC                          | [@madrigal2017]               |
| TSKCCA                         | [@yoshida2017]                |
| SMSMA                          | [@kawaguchi2017]              |
| AJIVE                          | [@feng2018]                   |
| MOFA                           | [@argelaguet2020]             |
| PCA+CCA                        | [@brown2018]                  |
| JACA                           | [@zhang2020]                  |
| iPCA                           | [@tang2021]                   |
| pCIA                           | [@min2019]                    |
| sSCCA                          | [@safo2018]                   |
| SWCCA                          | [@min2017]                    |
| OmicsPLS                       | [@bouhaddani2018]             |
| SCCA-BC                        | [@pimentel2018]               |
| WON-PARAFAC                    | [@kim2019]                    |
| BIDIFAC                        | [@lock2020]                   |
| maui                           | [@ronen2019]                  |
| SmCCNet                        | [@shi2019]                    |
| msPLS                          | [@csala2020]                  |
| MOTA                           | [@fan2020]                    |
| D-CCA                          | [@shu2020]                    |
| COMBI                          | [@hawinkel2020]               |
| DPCCA                          | [@gundersen2020]              |
| MEFISTO                        | [@velten2020]                 |
| MultiPower                     | [@tarazona2020]               |
: (#tab:appendix-methods) Integration methods available and their references.

<!-- #Check https://github.com/mikelove/awesome-multi-omics -->

-   [Bookdown](https://github.com/rstudio/bookdown/): The book about how to write this type of books.

-   [Bioconductor](https://bioconducto.org "Bioconductor"): The project about bioinformatics on R mostly related to sequencing technologies.

-   [CRAN](https://cran.r-project.org "CRAN"): The main archive of R extensions/packages for R.

-   [GitHub](https://github.com "GitHub"): Company which allows to freely host remote [git](https://git-scm.com/ "git") repositories of many projects, including some used or developed on this thesis.

# Software

Along the years of this thesis several pieces of software have been generated as well as packages.
Here they are listed for easier retrieval.
They are listed on two ways, one with a brief explanation and another one ordered by what software piece is used on each analysis.

## Listed

An improved/tested version of [RGCCA](https://github.com/llrs/RGCCA), some modifications on the internal functions to ease the maintenance as well as adding tests and sometimes improving the documentation.
Also modified so that it is possible to provide a vector of models so that the model of the first dimension is not the same as the model on the second dimension (not sure if mathematically speaking makes sense but from a biological one I think it might be interesting to have it).

Designed to be used with RGCCA I wrote the package [inteRmodel](https:github.com/llrs/inteRmodel) to ease the bootstrapping and model selection.

A package to design batches to avoid batch effect [experDesign](https://cran.r-project.org/package=experDesign) and its website on [GitHub](https://github.com/llrs/experDesign).

Explore the effects of the hyperparameters on RGCCA on the provided dataset of [gliomaData](https://github.com/llrs/gliomaData) (Originally provided [here](http://biodev.cea.fr/sgcca/)) there is this repository [sgcca_hyperparameters](https://github.com/llrs/sgcca_hyperparameters).

We used a pouchitis cohort published in this [article](https://dx.doi.org/10.1186/s13059-015-0637-x)[@morgan2015] that was used to compare how performs our method in other's dataset.
The code used can be found in [this repository](https://github.com/llrs/pouchitis).

Some functions used to explore the TRIM dataset ended up in the [integration](https://github.com/llrs/integration-helper) package.This include functions for correlation, network analysis, enrichment, normalization of metadata...

I developed a package to analyze sets and fuzzy sets [BaseSet](https://github.com/rOpenSci/BaseSet) (based on what I learned from a previous iteration of the [package](https://github.com/llrs/GSEAdv "GSEAdv package")).
This package was meant to be used with the probabilities that arise from bootstrapping the models.
However, due to the long times of calculation that it would require it was not used.

To analyze the antiTNF cohort (also named BARCELONA) a [different repository](https://github.com/llrs/Barcelona "Barcelona repository") was created to analyze the data using the previously developed packages.

## By project/publication

All code of the analysis of the publications is available (in his messed state and complicated history) and a brief description as to why they were used:

[Multi-omic modelling of inflammatory bowel disease with regularized canonical correlation analysis](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0246367):

-   [TRIM](https://github.com/llrs/TRIM "HSCT dataset exploration code on github"): Mangle with the sample, dataset, explore several methods...
-   [Puget's](https://github.com/llrs/sgcca_hyperparameters "RGCCA exploration code on github"): Explore the effects of the hyperparameters on RGCCA on the provided dataset.
-   [inteRmodel](https://github.com/llrs/inteRmodel "Integration package on github"): Package for easy repeating the methodology developed on TRIM.
-   [Morgan's](https://github.com/llrs/pouchitis "Pouchitis code on github"): Work with the pouchitis cohort used in this article.
-   [Häsler's](https://github.com/llrs/Uncoupling "Uncoupling code on github"): Work with the UC/CD dataset used in this article.
-   [integration](https://github.com/llrs/integration-helper "Integration package on github"): Package with functions that I wrote or used on different parts of exploring the TRIM dataset ended up here.

BaseSet:

-   [BaseSet](https://cran.r-project.org/package=BaseSet "BaseSet landing page on CRAN"): Fuzzy logic implementation, available on [rOpenSci too](https://github.com/ropensci/BaseSet "BaseSet git repository") and its [documentation website](https://docs.ropensci.org/BaseSet "BaseSet") .

experDesign:

-   [experDesign](https://cran.r-project.org/package=experDesign "experDesign landing page on CRAN"): Help design experiments in batches. It has a [documentation website too](https://experDesign.llrs.dev/ "experDesign").


BARCELONA:

- [BARCELONA](https://github.com/llrs/Barcelona): Code to analyze the BARCELONA's dataset

Validation:

-  [Howell's](https://github.com/llrs/howell_2018): Work with Howell's 2018 dataset. 
- [Cristian's](https://github.com/llrs/cristian_mark): Work with Cristian's 2020 dataset. 
