---
title: "My thesis"
author: "Lluís Revilla Sancho"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
# bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: llrs/thesis
description: "This is the home of the thesis."
---

# Preface {-}

The main topic of the thesis is [data
integration](https://en.wikipedia.org/wiki/Data_integration) applied in the
[inflammatory bowel disease
(IBD)](https://en.wikipedia.org/wiki/Inflammatory_bowel_disease) research. The
data I will be integrating are different omics data and the phenotype of the
patients. This disease is complex and there are hypothesis pointing that the
[microbiome](https://en.wikipedia.org/wiki/Microbiota) is a major factor in the
disease. In the precision medicine framework data integration is important to
consider all the relevant variables that influence a disease.

The thesis is performed on the [IDIBAPS](http://www.idibaps.org/) research
institute. My colleges are biologist, microbiologists, veterinaries... and we
have weekly meetings with the doctors visiting at the nearby hospital.

The thesis program allows one to defend the thesis after 3 years, and up to 5 in
total. My timeline is to finish in 3 years (I'll add it when it is finished to
see how it went :) with the guide of my thesis directors are Juanjo Lozano and
Azucena Sala, who help as bioinformatician and disease expert respectively.

